# content_creator.py
# v20.2.6 - Refactored main facade module

import narration_builder
import audio_generator
import subtitle_generator

# Re-export all public functions for backward compatibility
build_english_narration_news = narration_builder.build_english_narration_news
build_english_narration_deepdive = narration_builder.build_english_narration_deepdive
build_english_narration_comparison = narration_builder.build_english_narration_comparison
build_english_narration_spotlight = narration_builder.build_english_narration_spotlight
build_audio_script = narration_builder.build_audio_script

generate_segmented_voiceover = audio_generator.generate_segmented_voiceover
generate_single_voiceover = audio_generator.generate_single_voiceover

generate_subtitles = subtitle_generator.generate_subtitles
generate_subtitles_from_script = subtitle_generator.generate_subtitles_from_script

# Re-export fallback functions
get_fallback_deepdive_script = narration_builder.get_fallback_deepdive_script
get_fallback_news_script = narration_builder.get_fallback_news_script
get_fallback_comparison_script = narration_builder.get_fallback_comparison_script
get_fallback_spotlight_script = narration_builder.get_fallback_spotlight_script
get_fallback_narration = narration_builder.get_fallback_narration

# Re-export audio fallback functions
create_proper_silent_audio = audio_generator.create_proper_silent_audio
create_emergency_fallback_audio = audio_generator.create_emergency_fallback_audio
